Fix Key-Value Encrypted Store dropping new lines.
forcedotcom/SalesforceMobileSDK-Android pull request #2134
Opened 2020-10-09 01:21 UTC by brandonpage

2020-10-09 02:32 UTC, wmathurin requested changes
https://stackoverflow.com/questions/309424/how-do-i-read-convert-an-inputstream-into-a-string-in-java provides 11 ways to convert a stream to a string.
Some convert different line breaks to one.

It looks like the fastest and correct in all cases JDK based solution is solution 8:
```java
ByteArrayOutputStream result = new ByteArrayOutputStream();
byte[] buffer = new byte[1024];
int length;
while ((length = inputStream.read(buffer)) != -1) {
    result.write(buffer, 0, length);
}
// StandardCharsets.UTF_8.name() > JDK 7
return result.toString("UTF-8");
```

2020-10-09 17:37 UTC, wmathurin approved these changes
Could you check to see if we are doing the stream to string stuff the wrong way anywhere else in the codebase?

2020-10-11 16:43 UTC, bhariharan commented on libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/KeyValueEncryptedFileStore.java
> +            return value.toString("UTF-8");
```suggestion
            return value.toString(StandardCharsets.UTF_8);
```

2020-10-11 16:43 UTC, bhariharan commented on libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/KeyValueEncryptedFileStore.java
> +    private final int READ_BUFFER_LENGTH = 1024;
```suggestion
    private static final int READ_BUFFER_LENGTH = 1024;
```

2020-10-13 06:57 UTC, wmathurin approved these changes

2020-10-13 14:46 UTC, bhariharan requested changes

2020-10-13 14:46 UTC, bhariharan commented on libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/security/Encryptor.java
> +    public static String getStringFromStream(InputStream stream) throws IOException {
Add `Javadoc` since they're `public` methods.

2020-10-13 14:46 UTC, bhariharan commented on libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/security/Encryptor.java
> +        stream.close();
If an exception is thrown, the stream won't be closed. Put this in a `finally` block.

2020-10-13 23:11 UTC, bhariharan approved these changes

2020-10-13 23:45 UTC, merged