Setting cookies on hybrid remote webview instead of loading page through front door
forcedotcom/SalesforceMobileSDK-Android pull request #2618
Opened 2024-09-20 22:59 UTC by wmathurin

### New class: `SalesforceWebviewCookieManager`
- based on SApp's `BridgeCookieManager`
- Gets SIDs from the `UserAccount` and sets them in the `CookieManager`

### Modified `SalesforceDroidGapActivity`
- it no longer uses front-door to load remote app
- it calls `SalesforceWebviewCookieManager`'s `setCookies` method when receiving a refresh broadcast
- cleaned up the `reload` logic (previously called `refresh` but that name was a bit confusing)

### Manual testing
Created two apps on Mobile SDK cs4.com test org
- `apex/AccountEditor` which is the AccountEditor uploaded as hybrid remote app: it uses Mobile SDK Cordova plugins to do network operations
- `apex/AccountList` which is a true Visual Force app that shows a list of accounts and allow navigation to their detail screen

#### Testing steps with `apex/AccountEditor`
- login to hybrid remote app pointing to `apex/AccountEditor`
- do some operations (that talk to the server)
- from a browser in setup -> session management, kill the oauth2 parent session
- go back to application, do some operations
- check the log, it shows that a refresh took place but it was completely transparent to the user

#### Testing steps with `apex/AccountList`
- login to hybrid remote app pointing to `apex/AccountList`
- click on some account, it navigates to the account detail page
- from a browser in setup -> session management, kill the oauth2 parent session
- go back to application, navigate again to an account detail page
- check the log, it shows that a refresh followed by setCookies took place but they were completely transparent to the user

NB: the user experience is better than before, previously when a redirect to login took place, we would intercept, refresh and then reload the start page - now we are actually loading the page you are trying to get to

![HybridFlows](https://github.com/user-attachments/assets/e4bb2154-ceee-4b75-97be-c72326b81ba1)

2024-09-25 04:03 UTC, brandonpage requested changes
Code logic looks good, just a couple semver breaking changes.

2024-09-27 18:27 UTC, wmathurin commented on libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceDroidGapActivity.kt
> +        i(TAG, "reload called url:$url")
Reverted to refresh - see https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2618/commits/1623d19aee95d84dc6ea102661a0f326779d952e

2024-09-27 18:28 UTC, wmathurin commented on libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceDroidGapActivity.kt
> -    fun getFrontDoorUrl(
Method is back but marked as deprecated - see https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2618/commits/1623d19aee95d84dc6ea102661a0f326779d952e

2024-09-27 18:29 UTC, brandonpage approved these changes

2024-09-27 20:45 UTC, merged