Added Null check to prevent crash for TrailHead Go Android
forcedotcom/SalesforceMobileSDK-Android pull request #2633
Opened 2024-11-04 17:50 UTC by umashankar-sf

[com.salesforce.trailheadgo.app_issue_fa4327a6a3154091d49279fa5eba233c_crash_session_6722C99202280001286FF83BCF5223CF_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/17622028/com.salesforce.trailheadgo.app_issue_fa4327a6a3154091d49279fa5eba233c_crash_session_6722C99202280001286FF83BCF5223CF_DNE_0_v2_stacktrace.txt)

https://console.firebase.google.com/project/trailhead-go/crashlytics/app/android:com.salesforce.trailheadgo.app/issues/3acb1308797bc3f5179c50ae5d9d0335?time=last-ninety-days&types=crash&versions=4.1.1%20(4)%20(4010101)&sessionEventKey=672B3B16020000015F77FD9E92962BED_2012546185538799571

https://console.firebase.google.com/project/trailhead-go/crashlytics/app/android:com.salesforce.trailheadgo.app/issues/fa4327a6a3154091d49279fa5eba233c?time=last-ninety-days&types=crash&versions=4.1.1%20(4)%20(4010101)

2024-11-11 17:31 UTC, brandonpage commented on libs/SalesforceSDK/src/com/salesforce/androidsdk/security/AppLockManager.kt
> +    fun getPolicy(account: UserAccount?): Policy {
This is incorrect.  There are two places where this is API is used and both check the account is not null first.

2024-11-11 17:44 UTC, brandonpage requested changes
I don't understand what scenario this change is for.  When would the `options` Bundle ever be null?  

If you are launching the LoginActivity yourself (which I do not recommend) you need to supply the correct values so we can use them [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/a0e26fc4a3b340b6e72825abb205945f851053f7/libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.kt#L182).

2024-12-04 05:06 UTC, umashankar-sf commented
@brandonpage Please find the logs and screenshot from Firebase, It is crashing a lot for TrailHead GO app.

**Biometric crash Screenshot and Logs**
![image](https://github.com/user-attachments/assets/6212c2dc-8a7e-43f4-87d4-35399c21d900)

[biometric error.txt](https://github.com/user-attachments/files/18002826/biometric.error.txt)

**Bundle null Crash**
![image](https://github.com/user-attachments/assets/07d75482-5769-4450-abe3-9578736272e2)
[bundle null.txt](https://github.com/user-attachments/files/18002829/bundle.null.txt)

Let's connect if you need more details

2024-12-04 05:15 UTC, umashankar-sf commented
@brandonpage  [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/a0e26fc4a3b340b6e72825abb205945f851053f7/libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.kt#L182) the code is just passing `intent.extras` we are not checking null value.
`extras` is a nullable property. So this can be `null`. This is where crash is happening according to the Logs.
 In this PR I just added null check.

@zzou @jaewoo-lee 
```

val loginOptions = when {
            isUsingFrontDoorBridge -> salesforceSDKManager.loginOptions
            else -> fromBundleWithSafeLoginUrl(intent.extras)
        }

```

   ```
 /**
     * Retrieves a map of extended data from the intent.
     *
     * @return the map of all extras previously added with putExtra(),
     * or null if none have been added.
     */
    public @Nullable Bundle getExtras() {
        return (mExtras != null)
                ? new Bundle(mExtras)
                : null;
    }
```

2024-12-07 18:03 UTC, brandonpage commented
> @brandonpage Please find the logs and screenshot from Firebase, It is crashing a lot for TrailHead GO app.
> 
> **Biometric crash Screenshot and Logs** ![image](https://private-user-images.githubusercontent.com/178544153/392232388-6212c2dc-8a7e-43f4-87d4-35399c21d900.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1OTQ3MjUsIm5iZiI6MTczMzU5NDQyNSwicGF0aCI6Ii8xNzg1NDQxNTMvMzkyMjMyMzg4LTYyMTJjMmRjLThhN2UtNDNmNC04N2Q0LTM1Mzk5YzIxZDkwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwN1QxODAwMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05M2I0NTJmY2Y4NGUyM2YxN2NjNzg3MjZiYmY3OTZmZTQyYjZhOGFhODc2YWU5MjY3Yzc4NGEzNjJlMWU2ZTFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZEuYt7dNUOqFDw7Woq2uYGm7_yskyCR10nHeF8l1DIM)
> 
> [biometric error.txt](https://github.com/user-attachments/files/18002826/biometric.error.txt)


As I mentioned on Slack, is this not fixed by the`?` [null check here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/7de5ffc1392590cc60fce2cc4b8b6019ba292a40/libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.kt#L1430) introduced in Mobile SDK 12?

2024-12-07 19:27 UTC, brandonpage commented
> @brandonpage [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/a0e26fc4a3b340b6e72825abb205945f851053f7/libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.kt#L182) the code is just passing `intent.extras` we are not checking null value. `extras` is a nullable property. So this can be `null`. This is where crash is happening according to the Logs. In this PR I just added null check.

Sure, `intent.extras` is a nullable property but it should never be null on our or any subclass of our LoginActivity.  Everywhere that the login activity is called from uses `intent.extras`  to store our `LoginOptions` object.  This object is passed into `OAuthWebviewHelper` and is necessary for proper authentication and later token managment.  

We need to find out how the your app is getting into this state and fix the root cause, not add a null check that will let the app continue in a broken state.

2024-12-07 19:27 UTC, closed without merging